/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sheets;


import java.io.File;
import java.io.IOException;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonParser;

public class App {

    private static final String APPLICATION_NAME = "Google Sheets API Java Quickstart";
 //   private static final JsonFactory JSON_FACTORY = JacksonFactory.getDefaultInstance();
    private static final String TOKENS_DIRECTORY_PATH = "tokens";

    public String getGreeting() {

	try {
	JsonParser jsonParser = new JsonFactory().createParser(new File("employee.txt"));
	} 
	catch (IOException e){}

        return "Hello World!";




    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
